database:
  file: data\database
  username: user
  password: pass

settings:
  no-password: LOCK # NOTHING | PROMPT | LOCK
  remember-password: true
  reset-check: false
  distance: 30
  cooldown-time: 600 # in seconds
  length: 10
  broadcast: true
  broadcast-open: true
  steal-amount: 5
  steal-time: 7 # in seconds

tones:
  0: ENTITY_ENDERMAN_SCREAM
  1: ENTITY_ENDERMAN_TELEPORT
  2: ENTITY_ENDER_DRAGON_DEATH
  3: ENTITY_ENDERMAN_DEATH
  4: ENTITY_ENDERMAN_AMBIENT
  5: ENTITY_ENDERMAN_STARE
  6: ENTITY_ENDERMAN_HURT
  7: ENTITY_ENDERMAN_DEATH
  8: ENTITY_ENDER_DRAGON_FLAP
  9: ENTITY_ENDER_DRAGON_HURT

messages:
  broadcast: "&cSomeone tried to hack into your enderchest at x%x% y%y% z%z%"
  broadcast-open: "&cSomeone hacked into your enderchest at x%x% y%y% z%z%"
  prompt: "&cPlease set a password for your enderchest for security purpose"
  wrong-password: "&cWrong Password"
  steal-amount: "&cYou have reached the max limit for the items you can steal"
  cooldown: "&cYou are in a cooldown"
  max-length: "&cThe maximum length of a password is %length%"
  invalid-target: "&cPlease enter a valid target"
  distance: "&cYou need to be near a ender chest in order to use that command"
  play-tone: "&aPlayed the tone of the password"
  password-set: "&aSuccessfully changed your password"
  reset-password: "&aSuccessfully reset the password"
  no-permission: "&cYou don't have permission to use this"
  reload: "&cMortis Ender Phreak Reloaded"
  opened: "&aOpened the ender chest"
  no-remember: "&cRemember password is off"
  set-usage: "&cUsage: /enderphreak set newpass oldpass"
  invalid-number: "&cPlease enter a valid number"
  tone-usage: "&cUsage: /enderphreak tone <password>"
  pass-usage: "&cUsage: /enderphreak pass <password>"
  override-usage: "&cUsage: /enderphreak override <player-name>"
  override-reset-usage: "&cUsage: /enderphreak overridereset <player-name>"
  hack-usage: "&cUsage: /enderphreak hack <player-name> <password>"